import "@/style/globals.css";
import React from "react";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import {cn} from "@/script/utility/cn";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "Welcome | Sofa Machabba Haeta",
    description: "Generated by create next app",
};

export default function RootLayout({ children }: Readonly<{ children: React.ReactNode }>) {
    return (
        <html lang="en">
            <body className={ cn("min-h-screen bg-background font-sans antialiased", inter.className) }>
                {children}
            </body>
        </html>
    );
}